version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /home/ubuntu/myapp
  - source: scripts/
    destination: /home/ubuntu/scripts

permissions:
  - object: /home/ubuntu/myapp
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/verify_server.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
